encoding: utf-8

# SEO相关信息
title: LastJason Blog
description: LastJason的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
# footerText: 'Copyright © 2016 皖ICP备16016174号'

# 留言配置, 不需要的话值设置为空，同时删除 # 菜单 配置项中的留言页面
# 官网 https://www.bmob.cn
# 文档 https://bmob.github.io/hydrogen-js-sdk
# 建议自己申请一个，表结构如下
# 表名 Comment ,字段如下
# url      String
# time     Date
# nickName String
# email    String
# content  String
# website  String
bmobApplicationId: fdbfb281cff17d2bc036d9be5440960a
bmobRestApiKey: 6c7ce99a6be33849cb0189d75598d016

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
# domainUrl: 'http://blog.tmaize.net'
baseUrl: ''

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 自定义插件,具体说明请看README文档
customPlugins:
  - use: true
    file: 'plugin-mta-stats.html'
    sid: 500696527
    cid: 500696534
  - use: true
    file: 'plugin-baidu-push.html'
  - use: true
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']
